
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 27 19:38:18 CEST 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 33;
  public static final int FSI = 32;
  public static final int TANTQUE = 23;
  public static final int CONSTANTECHAINE = 28;
  public static final int MULT = 4;
  public static final int EGAL = 17;
  public static final int REPETER = 24;
  public static final int SI = 29;
  public static final int VIRGULE = 9;
  public static final int FIN = 20;
  public static final int LIRE = 22;
  public static final int OU = 15;
  public static final int INF = 11;
  public static final int NON = 16;
  public static final int PAROUV = 6;
  public static final int DIV = 5;
  public static final int EGALEGAL = 12;
  public static final int PLUS = 2;
  public static final int DEBUT = 19;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RETOURNE = 34;
  public static final int MOINS = 3;
  public static final int ET = 14;
  public static final int SINON = 31;
  public static final int IDF = 21;
  public static final int ALORS = 30;
  public static final int PARFER = 7;
  public static final int CONSTANTEINT = 26;
  public static final int CONSTANTEBOOL = 27;
  public static final int PROGRAMME = 18;
  public static final int POINTVIRGULE = 8;
  public static final int FINTANTQUE = 25;
  public static final int SUP = 10;
  public static final int DIFF = 13;
  public static final int ENTIER = 35;
  public static final int ECRIRE = 36;
}

