
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 13 13:41:20 CET 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 17;
  public static final int EGAL = 16;
  public static final int OU = 14;
  public static final int PLUS = 2;
  public static final int SUP = 9;
  public static final int ECRIRE = 23;
  public static final int NON = 15;
  public static final int MOINS = 3;
  public static final int INF = 10;
  public static final int POINTVIRGULE = 8;
  public static final int PARFER = 7;
  public static final int ENTIER = 22;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int EGALEGAL = 11;
  public static final int DIV = 5;
  public static final int CONSTANTEBOOL = 19;
  public static final int ET = 13;
  public static final int error = 1;
  public static final int CONSTANTEIDF = 21;
  public static final int PAROUV = 6;
  public static final int CONSTANTECHAINE = 20;
  public static final int DIFF = 12;
  public static final int CONSTANTEINT = 18;
}

